/*
 * This source file was generated by the Gradle 'init' task
 */
package hexlet.code;

import java.util.Scanner;

public class App {
    private static Scanner scanner = null;

    public static String getGreeting() {
        String greetAndAskName = "\nWelcome to the Brain Games!\nMay I have your name? ";
        System.out.print(greetAndAskName);
        String name = scanner.next();
        String hello = "Hello, " + name + "!";
        System.out.println(hello);
        return name;
    }

    public static void main(String[] args) {
        System.out.println("Please enter the game number and press Enter.");
        System.out.println("1 - Greet");
        System.out.println("2 - Even");
        System.out.println("3 - Calc");
        System.out.println("4 - GCD");
        System.out.println("5 - Progression");
        System.out.println("6 - Prime");
        System.out.println("0 - Exit");
        System.out.print("Your choice: ");
        // App app = new App();
        scanner = new Scanner(System.in);
        int choice = scanner.nextInt();
        if (choice != 0) {
            var name = getGreeting();
            Engine.makeGame(name, choice);
        }
        scanner.close();
    }
}
